name: phishing-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip
  - pip:
    - huggingface_hub
    - fire
    - datasets
    - peft
    - transformers
    - accelerate
    - bitsandbytes
    - torch

